#!/bin/bash -e

NAME="coreos-cloudinit"
ORG_PATH="github.com/flatcar"
REPO_PATH="${ORG_PATH}/${NAME}"
VERSION=$(git describe --dirty --tags)
GLDFLAGS="-X main.version=\"${VERSION}\""
GOBIN=${GOBIN:-$PWD/bin}
export GOBIN

go build -ldflags "${GLDFLAGS}" -o $(go env GOBIN)/${NAME} .
